### ISSUE TITLE
GPodderSync would grey out the "Fetch" button when the locale is set to Japanese

### ISSUE THREAD

**Issue by felixleong** [pschwede/quodlibet-plugins#1]
When running Quodlibet in Japanese, the `app.browser.name == u'Audio Feed` check would fail as it'd return the localized name.

A more appropriate check that works would be:

```python
from quodlibet.browsers.audiofeeds import AudioFeeds

correct_browser = isinstance(app.browser, AudioFeeds)

# And in the update_feeds() section
if not isinstance(app.browser, AudioFeeds):
    print_d("Wrong browser!")
    return
```

**Comment by lazka** [comment]
I don't think we have a gpodder plugin. Did you install it from somewhere else maybe?

**Comment by lazka** [comment]
oh, wrong repo :P didn't know I was subscribed here. Never mind my comment above.

**Comment by pschwede** [comment]
Thanks for helping out. And thanks for trying out my plugins :)
